CREATE TABLE IF NOT EXISTS urls (
    id UUID PRIMARY KEY,
    code VARCHAR(36) NOT NULL,
    origin_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
); 